# Generated by Django 3.0.6 on 2020-05-22 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobsearch', '0004_auto_20200517_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('no', 'Не ищу работу'), ('maybe', 'Рассматриваю предложения'), ('yes', 'Ищу работу')], default=None, max_length=100)),
                ('grade', models.CharField(choices=[('intern', 'Стажер'), ('junior', 'Джуниор'), ('moddle', 'Мидл'), ('senior', 'Синьор'), ('lead', 'Лид')], default=None, max_length=100)),
                ('salary', models.IntegerField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('expirience', models.CharField(max_length=100)),
                ('portfolio', models.CharField(max_length=100)),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='jobsearch.Specialty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
